name: Update Ontario road map
on:
  schedule:
    - cron: 0 0/1 * * *

jobs:
  update_map:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python 3.10.2
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.2"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Chart update and publish
        env: 
            DW_AUTH_TOKEN: ${{ secrets.DW_AUTH_TOKEN }}
        run: python3 on_traffic.py
        
